#!/bin/bash
#
# register_types.sh - Generator for register_types.cpp and register_types.h
#
# This script scans the directory recursively for GDCLASS definitions and
# generates the corresponding registration code.
#

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Output files
HEADER_FILE="$SCRIPT_DIR/register_types.h"
CPP_FILE="$SCRIPT_DIR/register_types.cpp"

# Temporary file for collecting class names
CLASSES_FILE=$(mktemp)
trap "rm -f $CLASSES_FILE" EXIT

# Find all GDCLASS definitions recursively
echo "Scanning for GDCLASS definitions..."

# Search for GDCLASS patterns in header files (excluding godot-cpp and vcpkg)
grep -r "GDCLASS\s*(" "$SCRIPT_DIR" \
    --include="*.h" \
    --include="*.hpp" \
    --exclude-dir="godot-cpp" \
    --exclude-dir="vcpkg" 2>/dev/null | \
    sed -E 's/.*GDCLASS\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,.*/\1/' | \
    sort | uniq > "$CLASSES_FILE"

# Count found classes
CLASS_COUNT=$(wc -l < "$CLASSES_FILE")

if [ "$CLASS_COUNT" -eq 0 ] || [ ! -s "$CLASSES_FILE" ]; then
    echo "Warning: No GDCLASS definitions found!"
else
    echo "Found $CLASS_COUNT class(es):"
    sed 's/^/  - /' "$CLASSES_FILE"
fi

# Generate register_types.h
echo ""
echo "Generating $HEADER_FILE..."
cat > "$HEADER_FILE" << 'EOF'
// register_types.h - Header for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#ifndef REGISTER_TYPES_H
#define REGISTER_TYPES_H

#include "gdextension_interface.h"
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

using namespace godot;

void gdext_initialize_module(ModuleInitializationLevel p_level);

void gdext_uninitialize_module(ModuleInitializationLevel p_level);

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool;
}

#endif // REGISTER_TYPES_H
EOF

# Generate register_types.cpp
echo "Generating $CPP_FILE..."

# Start building the CPP file
{
    cat << 'EOF'
// register_types.cpp - Implementation for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#include "register_types.h"

#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

#include "gdextension_interface.h"

// Include headers for all detected classes
EOF

    # Find and include all header files that contain GDCLASS definitions
    grep -r "GDCLASS\s*(" "$SCRIPT_DIR" \
        --include="*.h" \
        --include="*.hpp" \
        --exclude-dir="godot-cpp" \
        --exclude-dir="vcpkg" 2>/dev/null | \
        cut -d: -f1 | \
        sort | uniq | \
        sed "s|$SCRIPT_DIR/||" | \
        sed 's/^/#include "/' | \
        sed 's/$/"/'

    cat << 'EOF'

using namespace godot;

void gdext_initialize_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }

    // Register all discovered wrapper classes
EOF

    # Add GDREGISTER_CLASS calls for each class
    while IFS= read -r classname; do
        if [ -n "$classname" ]; then
            echo "    GDREGISTER_CLASS($classname);"
        fi
    done < "$CLASSES_FILE"

    cat << 'EOF'
}

void gdext_uninitialize_module(ModuleInitializationLevel p_level) {
    (void)p_level;
    // Teardown logic (if any) goes here.
}

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool {
        godot::GDExtensionBinding::InitObject const init_obj(
            p_get_proc_address, p_library, r_initialization
        );

        init_obj.register_initializer(gdext_initialize_module);
        init_obj.register_terminator(gdext_uninitialize_module);
        init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

        return init_obj.init();
    }
}
EOF
} > "$CPP_FILE"

echo "Done!"
echo ""
echo "Summary:"
echo "  - Header: $HEADER_FILE"
echo "  - Implementation: $CPP_FILE"
