// register_types.h - Header for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#ifndef REGISTER_TYPES_H
#define REGISTER_TYPES_H

#include "gdextension_interface.h"
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

using namespace godot;

void gdext_initialize_module(ModuleInitializationLevel p_level);

void gdext_uninitialize_module(ModuleInitializationLevel p_level);

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool;
}

#endif // REGISTER_TYPES_H
