// register_types.cpp - Implementation for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#include "register_types.h"

#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

#include "gdextension_interface.h"

// Include headers for all detected classes
#include "autowrapper/Sqlite3Wrapper.h"

using namespace godot;

void gdext_initialize_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }

    // Register all discovered wrapper classes
    GDREGISTER_CLASS(Fts5ApiHandle);
    GDREGISTER_CLASS(Fts5contextHandle);
    GDREGISTER_CLASS(Fts5extensionapiHandle);
    GDREGISTER_CLASS(Fts5phraseiterHandle);
    GDREGISTER_CLASS(Fts5tokenizerHandle);
    GDREGISTER_CLASS(Fts5TokenizerHandle);
    GDREGISTER_CLASS(Fts5TokenizerV2Handle);
    GDREGISTER_CLASS(Sqlite3ApiRoutinesHandle);
    GDREGISTER_CLASS(Sqlite3BackupHandle);
    GDREGISTER_CLASS(Sqlite3BlobHandle);
    GDREGISTER_CLASS(Sqlite3ChangegroupHandle);
    GDREGISTER_CLASS(Sqlite3ChangesetIterHandle);
    GDREGISTER_CLASS(Sqlite3ContextHandle);
    GDREGISTER_CLASS(Sqlite3FileHandle);
    GDREGISTER_CLASS(Sqlite3FilenameHandle);
    GDREGISTER_CLASS(Sqlite3Handle);
    GDREGISTER_CLASS(Sqlite3IndexInfoHandle);
    GDREGISTER_CLASS(Sqlite3IoMethodsHandle);
    GDREGISTER_CLASS(Sqlite3MemMethodsHandle);
    GDREGISTER_CLASS(Sqlite3ModuleHandle);
    GDREGISTER_CLASS(Sqlite3MutexHandle);
    GDREGISTER_CLASS(Sqlite3MutexMethodsHandle);
    GDREGISTER_CLASS(Sqlite3PcacheHandle);
    GDREGISTER_CLASS(Sqlite3PcacheMethods2Handle);
    GDREGISTER_CLASS(Sqlite3PcacheMethodsHandle);
    GDREGISTER_CLASS(Sqlite3PcachePageHandle);
    GDREGISTER_CLASS(Sqlite3RebaserHandle);
    GDREGISTER_CLASS(Sqlite3RtreeGeometryHandle);
    GDREGISTER_CLASS(Sqlite3RtreeQueryInfoHandle);
    GDREGISTER_CLASS(Sqlite3SessionHandle);
    GDREGISTER_CLASS(Sqlite3SnapshotHandle);
    GDREGISTER_CLASS(Sqlite3StmtHandle);
    GDREGISTER_CLASS(Sqlite3StrHandle);
    GDREGISTER_CLASS(Sqlite3ValueHandle);
    GDREGISTER_CLASS(Sqlite3VfsHandle);
    GDREGISTER_CLASS(Sqlite3VtabCursorHandle);
    GDREGISTER_CLASS(Sqlite3VtabHandle);
    GDREGISTER_CLASS(Sqlite3Wrapper);
}

void gdext_uninitialize_module(ModuleInitializationLevel p_level) {
    (void)p_level;
    // Teardown logic (if any) goes here.
}

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool {
        godot::GDExtensionBinding::InitObject const init_obj(
            p_get_proc_address, p_library, r_initialization
        );

        init_obj.register_initializer(gdext_initialize_module);
        init_obj.register_terminator(gdext_uninitialize_module);
        init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

        return init_obj.init();
    }
}
